spring:
#    datasource:
#        url: mysql://nb48on2fxjq8cp81:ti6bc7nzpnnanfo1@q7cxv1zwcdlw7699.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/qspffctcoqvyv9vc
#        username: nb48on2fxjq8cp81
#        password: ti6bc7nzpnnanfo1
#        driver-class-name: com.mysql.jdbc.Driver
    flyway.locations: classpath:/db/migration,classpath:/db/migration_mock
    jpa:
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate.ddl-auto: validate
        show-sql: true
initial-strategy: SINGLE_LOCATION
distance-api: GOOGLE_DISTANCE_MATRIX
google-api-key: AIzaSyC19ZDeu_knnKSr15mFt_c1uwTeJHnE0xY
server.port: 8090
