spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: OnlineShopMongoDB
    datasource:
        url: jdbc:mysql://localhost:3306/online_shop_testing_schema?useSSL=false
        username: root
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver
    flyway.locations: classpath:/db/migration,classpath:/db/migration_mock
    jpa:
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate.ddl-auto: validate
        show-sql: false
initial-strategy: SINGLE_LOCATION
distance-api: GOOGLE_DISTANCE_MATRIX
google-api-key: AIzaSyC19ZDeu_knnKSr15mFt_c1uwTeJHnE0xY
client_id: my-trusted-client
client_secret: secret
authorized_grant_types: password,authorization_code,refresh_token
authorization_code: authorization_code
refresh_token: refresh_token
implicit: implicit
scope: read,write,trust
access_token_validity_seconds: 36000
refresh_token_validity_seconds: 36000
server.port: 8090
