##MySQL settings
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/online_shop_schema?useSSL=false
        username: root
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver
## This is important for flyway; Hibernate ddl auto (create, create-drop, validate, update)
    jpa:
        hibernate.ddl-auto: create
        properties: hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
    flyway:
        enabled: false
        locations: classpath:/db/migration
##Logging
#logging.level.org.springframework=debug
initial-strategy: singleLocation
#strategy.initial=singleLocation