spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: OnlineShopMongoDB
    datasource:
        url: jdbc:mysql://localhost:3306/online_shop_testing_schema?useSSL=false
        username: root
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver
    flyway.locations: classpath:/db/migration,classpath:/db/migration_mock
    jpa:
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate.ddl-auto: validate
        show-sql: true
initial-strategy: SINGLE_LOCATION
distance-api: GOOGLE_DISTANCE_MATRIX
google-api-key: AIzaSyC19ZDeu_knnKSr15mFt_c1uwTeJHnE0xY
client_id: my-trusted-client
client_secret: secret
grant_type: password
authorization_code: authorization_code
refresh_token: refresh_token
implicit: implicit
scope_read: read
scope_write: write
scope_trust: trust
access_token_validity_seconds: 300
refresh_token_validity_seconds: 600
product_manager: ROLE_PRODUCT_MANAGER
customer: false
administrator: false
server.port: 8090
