insert into product (id, name, price, category_id, image) values (1, 'Samsung Galaxy S8', 500, 1, 'https://drop.ndtv.com/TECH/product_database/images/329201783846PM_635_samsung_galaxy_s8.jpeg?downsize=770:*&output-quality=70&output-format=webp');
insert into product (id, name, price, category_id, image) values (2, 'Iphone X', 850, 1, 'asd');
insert into product (id, name, price, category_id, image) values (3, 'One Plus 6T', 650, 1, 'https://gloimg.gbtcdn.com/soa/gb/pdm-product-pic/Electronic/2018/11/02/goods_img_big-v1/20181102113847_24111.jpg');
insert into product (id, name, price, category_id, image) values (4, 'HP Pavilion', 800, 2, 'https://img.purch.com/o/aHR0cHM6Ly93d3cubGFwdG9wbWFnLmNvbS9pbWFnZXMvdXBsb2Fkcy80Njk4L2cvcGF2aWxpb24tMTUtZ2FtaW5nLWxlYWQuanBn');
insert into product (id, name, price, category_id, image) values (5, 'Asus ROG', 1000, 2, 'https://www.excaliberpc.com/images/675442_1/large.jpg');
insert into product (id, name, price, category_id, image) values (6, 'Acer Predator', 1250, 2, 'https://p1.akcdn.net/mid/520469928.acer-predator-helios-300-ph317-52-7429-nh-q3deu-016.jpg');
insert into product (id, name, price, category_id, image) values (7, 'XBOX ONE', 300, 3, 'http://www.orcaconservancy.org/wp-content/uploads/2018/06/Xbox-one.jpg');
insert into product (id, name, price, category_id, image) values (8, 'PS4', 400, 3, 'https://images-na.ssl-images-amazon.com/images/I/71pFB-gWFdL._SL1500_.jpg');
insert into product (id, name, price, category_id, image) values (9, 'Nintendo Switch', 200, 3, 'https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/204506-L-HI.jpg');
insert into product (id, name, price, category_id, image) values (10, 'FIFA 19', 60, 4, 'https://img-cache.coolshop.com/08c23d8f-e95e-44a3-be1e-19ea9b41be84/fifa-19-nordic.jpg?width=580');
insert into product (id, name, price, category_id, image) values (11, 'CS:GO', 12, 4, 'https://www.gamepressure.com/gallery/html/article/450797171.jpg');
insert into product (id, name, price, category_id, image) values (12, 'Call of Duty Black Ops 4', 70, 4, 'https://images-na.ssl-images-amazon.com/images/I/81GN6gepa5L._SL1500_.jpg');
insert into product (id, name, price, category_id, image) values (13, 'Samsung TV 4K', 1500, 5, 'https://image-us.samsung.com/SamsungUS/home/televisions-and-home-theater/tvs/4k-uhd/pdp/un65nu8000fxza/1_UN65NU8000FXZA_001_Front_Black_013018.jpg?$product-details-jpg$');
insert into product (id, name, price, category_id, image) values (14, 'Sony TV', 600, 5, 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5875/5875644_sd.jpg;maxHeight=640;maxWidth=550');
insert into product (id, name, price, category_id, image) values (15, 'Philips TV', 1000, 5, 'https://locations.colortyme.com/massachusetts/lawrence/images/stories/virtuemart/product/philips_50_led_hdtv_led_50PFL4909_lrg.jpg');
insert into product (id, name, price, category_id, image) values (16, 'Trust Speakers', 50, 6, 'https://images.mobilefun.co.uk/graphics/450pixelp/19639.jpg');
insert into product (id, name, price, category_id, image) values (17, 'Logitech Speakers', 200, 6, 'https://www.quietpc.com/images/products/logitech-z506.jpg');
insert into product (id, name, price, category_id, image) values (18, 'Alesis Speakers', 100, 6, 'https://masters-of-music.com/wp-content/uploads/2016/07/Alesis-Elevate-5-Studio-Monitor-Speakers.jpg');